# Generated by Django 6.0.7 on 2026-07-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('terrestre', 'Terrestre'), ('aereo', 'Aéreo'), ('acuatico', 'Acuático/Anfibio'), ('espacial', 'Nave espacial')], max_length=20)),
                ('capacidad', models.IntegerField(help_text='Número de tripulantes')),
                ('fecha_introduccion', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('rifle_asalto', 'Rifle de asalto'), ('rifle_battle', 'Battle Rifle'), ('pistola', 'Pistola'), ('escopeta', 'Escopeta'), ('francotirador', 'Rifle de francotirador'), ('energia', 'Arma de energía (Covenant/Forerunner)'), ('explosivo', 'Lanzacohetes / Explosivo'), ('cuerpo_a_cuerpo', 'Cuerpo a cuerpo')], max_length=30)),
                ('dano', models.IntegerField(help_text='Daño estimado por impacto (1-100)')),
                ('fecha_introduccion', models.DateField(help_text='Fecha/año en que aparece por primera vez en la saga')),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
