# Generated by Django 4.2.30 on 2026-07-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0002_seed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('humano', 'Humano'), ('inteligencia_artificial', 'Inteligencia Artificial'), ('elites', 'Sangheili'), ('grunts', 'Unggoy'), ('brutes', 'Jiralhanae'), ('prophets', "San'Shyuum")], max_length=25)),
                ('fecha_introduccion', models.DateField(help_text='Fecha/año en que aparece por primera vez en la saga')),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
