# Generated by Django 4.2.30 on 2026-07-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0003_characters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField(help_text='Costo del Juego en MXN')),
                ('consola', models.CharField(choices=[('pc', 'PC'), ('xbox', 'XBOX'), ('xbox_360', 'Xbox 360'), ('xbox_one', 'Xbox One'), ('xbox_one', 'Xbox One')], max_length=25)),
                ('fecha_introduccion', models.DateField(help_text='Fecha/año en que aparece por primera vez en la saga')),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
