# Generated by Django 4.2.30 on 2026-07-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory', '0004_saga'),
    ]

    operations = [
        migrations.AddField(
            model_name='saga',
            name='armas_disponibles',
            field=models.ManyToManyField(blank=True, related_name='sagas', to='armory.weapon'),
        ),
    ]
